### PR TITLE
remove api details from nextjs getting started, fix typo in react

### PR DESCRIPTION
**Pull request by sublimezeal**
### Description 

1) Getting Started nextjs guide:
 - removed details for creating identities and passkeys via API, added link to where this guidance lives in the Hosted Web -> Add passkeys to your app guide
 - added specific guidance to create identity and passkey via console for testing purposes
 2) Getting Started react guide:
 - fixed typo

### CODE REVIEW

**Review by Will5 — COMMENTED** [review]
At [L236](https://github.com/gobeyondidentity/developer-docs/pull/292/files#diff-7ad37f1921e9fbfefc28c5f6a13fc42f7152e6735183b47b82923d6c960bb0efL236) you have "https://auth-us." I would suggest "https://auth-${process.env.REGION}."

**Review by Will5 — COMMENTED** [review]
For the environment variables in the .env.local file, you have `API_TOKEN` and `AUTHENTICATOR_CONFIG_ID`, but they are not used anywhere. I think we can remove these, as neither NextAuth nor the WellKnown URL requires them.

**Review by Will5 — COMMENTED** [review]
In regards to the port, in some cases we have `{your_app's_port}` and in some cases we have `8083`. We should probably keep these consistent, in case the user is not using 8083. The NextAuth example app seems to default to `3000`.

**Comment by sublimezeal** [comment]
> In regards to the port, in some cases we have `{your_app's_port}` and in some cases we have `8083`. We should probably keep these consistent, in case the user is not using 8083. The NextAuth example app seems to default to `3000`.

Just made them all 3000

**Review by Will5 — APPROVED** [review]

**Pull request merged**
